POST http://localhost:7071/api/plugins/EditingPlugin/functions/GeographicAbbreviations
content-type: application/json

{
    "input":"The states of Kentucky, Massachusetts and Pennsylvania have the designation of commonwealths. Therefore citizens of Lexington (KY), Lenox (MA) and Philadelphia (PE) are called commoners."
}

###

POST http://localhost:7071/api/plugins/EditingPlugin/functions/ChangeTense
content-type: application/json

{
    "input":"Every morning, Sparkle scampers out of her cozy nest high up in the enchanted oak tree. Her bushy tail twitches with excitement as she explores the forest. She hops from one moss-covered rock to another, her tiny paws leaving sparkling footprints behind.",
    "tense": "present perfect"
}

###

POST http://localhost:7071/api/plugins/EditingPlugin/functions/RunningText
content-type: application/json

{
    "input":""
}

###

POST http://localhost:7071/api/planner
content-type: application/json

{
    "input":"I want to go to the movies"
}

### 

#POST http://localhost:7071/api/transform
POST https://chimera-sk-functions.azurewebsites.net/api/transform
content-type: application/json

{
    "content": {
        "Document Title: Examination of the Stability of TAK-188 in Mouse, Monkey, and Human Plasma": "Document Version: 1.0Effective Date: 14 Apr 2023 14:22:20 (GMT-04:00)Signed By : Guo, Yukuang (mne9509) Decision : ApprovedDecision Date : 14 Apr 2023 13:52:28 (GMT-04:00)Role : Approver Purpose : ApprovalMeaning Of Signature : I approve this documentSigned By : Zhu, Xiaochun Sean (UBN7028) Decision : ApprovedDecision Date : 14 Apr 2023 14:22:06 (GMT-04:00)Role : Approver Purpose : ApprovalMeaning Of Signature : I approve this documentSignature Manifestation Page 1 of 1NONCLINICAL STUDY PROTOCOLMetabolism Identification Title:Examination of the Stability of TAK-188 in Mouse, Monkey, and Human Plasma Protocol:TKD-BCS-01991Testing Facility:Takeda Development Center Americas, Inc.35 Landsdowne StreetCambridge, MA 02139 USAStudy Director:Yukuang Guo Ph (312) 722-0479Proposed Study Dates:Experimental Start: 01 April 2023Experimental End: 01 July 2023",
        "INTRODUCTION": "CCR8 expression is upregulated on a highly immunosuppressive subset of regulatory T cells (Tregs) in multiple cancer types. TAK-188 is an Antibody Drug Conjugate (ADC) targeting CCR8. TAK-188 is designed specifically for depleting Tregs and boosting the immune system to produce an antitumoral effect.",
        "STUDY OBJECTIVE": "The objective of this study is to examine the plasma stability of TAK-188 in vitro in fresh mouse, monkey, and human plasma.",
        "REGULATORY GUIDELINES": "",
        "Good Laboratory Practice Compliance": "This study will not be conducted in accordance with the Code of Federal Regulations, Title 21, Part 58: Good Laboratory Practice for Nonclinical Laboratory Studies, issued by the United States Food and Drug Administration. However, this study will be conducted according to standard departmental practices.",
        "Amendments To, and Deviations From, the Protocol": "Any changes to the protocol will be described in a written protocol amendment approved by the Study Director specified in this protocol and recorded in the raw data at Takeda Development Center Americas, Inc. (TDCA) (Cambridge, MA, USA). Any deviations from the protocol will be documented appropriately and listed in the final report.",
        "TESTING FACILITY": "All aspects of this study will be conducted by personnel of TDCA (Cambridge, MA, USA).",
        "STUDY PERSONNEL": "Table 1 lists personnel involved in this study.",
        "PROPOSED STUDY SCHEDULE": "Table 2 provides the proposed study schedule.",
        "Table 2Proposed Study Schedule": "91440052510Study ComponentProposed DateExperimental start date:01 April 2023Experimental end date:01 July 202390525641553",
        "MATERIALS": "Unless otherwise stated, all analytical reagents will be at least of high-performance liquid chromatography (HPLC) reagent grade. Unless otherwise noted, all chemicals, with the exception of the test article (TAK-188) will be purchased from Sigma-Aldrich Corp (St. Louis, MO, USA) or supplied by personnel of TDCA’s Lab Operations group. All reagents, with the exception of the test article, will be less than 5 years old or formulated by personnel of TDCA’s Lab Operations group.",
        "Test Article": "TAK-188 will be supplied by personnel of TDCA’s Sample Bank and stored at approximately −20°C.The test article is early, research-grade material, which has not been completely characterized for identity, purity, and stability, and which does not have a Certificate of Analysis. The identity, storage temperature, lot (batch) numbers, and formulation requirements will be documented in the study file.",
        "Test System": "Fresh mouse, monkey, and human plasma will be purchased from external vendor (information will be provided in the final report).",
        "Reagents and Instruments": "The reagents and instruments used in this study will be specified in the raw data and final report.",
        "ASSAY METHODOLOGY": "",
        "Plasma incubation": "The experimental procedure and final conditions will be specified in the final report. The incubation will be run in triplicates. The incubation conditions are shown in Table 3.",
        "Table 3Incubation Conditions": "91440052480Matrix:Fresh plasmaSpecies:Mouse, monkey, humanTime (hours):0, 4, and 24Concentration (µg/mL):100Incubator Conditions:5% CO2, ~93% humidity, 37°CShaking Rate (rpm):7591440041438rpm: revolutions per minute.",
        "BIOANALYSIS": "The monkey and human samples will be shipped to Frontage Laboratories and mouse samples will be shipped to QPS for bioanalysis (the method and details will be included in the final report) as shown below:Frontage Laboratories Attn: Sample Management 700 Pennsylvania DriveExton, PA 1943Email: Sample_Management@frontagelab.com Phone: (610) 232-0100Attn: Sample Coordinator/Lan Li QPS, LLC3 Innovation WayNewark, DE 19711Tel: (302) 369-5120Fax: (302) 369-5602Email: sample@qps.com",
        "DATA INTERPRETATION AND REPORTING": "The Study Director, with participation by other contributing scientists, as appropriate, will prepare a report describing, but not necessarily be limited to, the following: a summary of the study, study objectives, materials and methods, and results and interpretation, including any appropriate tables, figures, and/or appendices.",
        "REMEASUREMENT AND ADOPTION OF THE DATA": "If the Study Director believes that a certain event (eg, technical error, instrumentation problem, or scientifically unexpected phenomena) may have affected the reliability of the present study, the Study Director may deem it necessary to repeat the experiment(s) in the study. The reasons for repeating any steps of an experiment, and for adoption or exclusion of the results, will be noted in the raw data and the final report.",
        "ARCHIVING": "All study data, including the protocol (with any amendments and deviations), final report, study file, laboratory study notebooks, instrument printouts, and other raw data or materials from the study will be maintained at TDCA according to standard departmental procedures.Title:    Examination of the Stability of TAK-188 in Mouse, Monkey, and Human Plasma",
        "PROTOCOL APPROVAL": "(see electronic signature page)91440042931Yukuang Guo Study Director Scientist IDrug Metabolism and Pharmacokinetics(see electronic signature page)91440041471Xiaochun Sean Zhu Scientific DirectorDrug Metabolism and Pharmacokinetics"
    },
    "headers": {
        "TAK": "TAK-188",
        "TKD": "TKD-BCS-01991"
    }
}


###
POST http://localhost:7071/api/startOrchestrator
content-type: application/json

{
    "content": {
        "Document Title: Examination of the Stability of TAK-188 in Mouse, Monkey, and Human Plasma": "Document Version: 1.0Effective Date: 14 Apr 2023 14:22:20 (GMT-04:00)Signed By : Guo, Yukuang (mne9509) Decision : ApprovedDecision Date : 14 Apr 2023 13:52:28 (GMT-04:00)Role : Approver Purpose : ApprovalMeaning Of Signature : I approve this documentSigned By : Zhu, Xiaochun Sean (UBN7028) Decision : ApprovedDecision Date : 14 Apr 2023 14:22:06 (GMT-04:00)Role : Approver Purpose : ApprovalMeaning Of Signature : I approve this documentSignature Manifestation Page 1 of 1NONCLINICAL STUDY PROTOCOLMetabolism Identification Title:Examination of the Stability of TAK-188 in Mouse, Monkey, and Human Plasma Protocol:TKD-BCS-01991Testing Facility:Takeda Development Center Americas, Inc.35 Landsdowne StreetCambridge, MA 02139 USAStudy Director:Yukuang Guo Ph (312) 722-0479Proposed Study Dates:Experimental Start: 01 April 2023Experimental End: 01 July 2023",
        "INTRODUCTION": "CCR8 expression is upregulated on a highly immunosuppressive subset of regulatory T cells (Tregs) in multiple cancer types. TAK-188 is an Antibody Drug Conjugate (ADC) targeting CCR8. TAK-188 is designed specifically for depleting Tregs and boosting the immune system to produce an antitumoral effect.",
        "STUDY OBJECTIVE": "The objective of this study is to examine the plasma stability of TAK-188 in vitro in fresh mouse, monkey, and human plasma.",
        "MATERIALS": "Unless otherwise stated, all analytical reagents will be at least of high-performance liquid chromatography (HPLC) reagent grade. Unless otherwise noted, all chemicals, with the exception of the test article (TAK-188) will be purchased from Sigma-Aldrich Corp (St. Louis, MO, USA) or supplied by personnel of TDCA’s Lab Operations group. All reagents, with the exception of the test article, will be less than 5 years old or formulated by personnel of TDCA’s Lab Operations group.",
        "Test Article": "TAK-188 will be supplied by personnel of TDCA’s Sample Bank and stored at approximately −20°C.The test article is early, research-grade material, which has not been completely characterized for identity, purity, and stability, and which does not have a Certificate of Analysis. The identity, storage temperature, lot (batch) numbers, and formulation requirements will be documented in the study file.",
        "Test System": "Fresh mouse, monkey, and human plasma will be purchased from external vendor (information will be provided in the final report).",
        "Plasma incubation": "The experimental procedure and final conditions will be specified in the final report. The incubation will be run in triplicates. The incubation conditions are shown in Table 3.",
        "Table 3Incubation Conditions": "91440052480Matrix:Fresh plasmaSpecies:Mouse, monkey, humanTime (hours):0, 4, and 24Concentration (µg/mL):100Incubator Conditions:5% CO2, ~93% humidity, 37°CShaking Rate (rpm):7591440041438rpm: revolutions per minute.",
        "BIOANALYSIS": "The monkey and human samples will be shipped to Frontage Laboratories and mouse samples will be shipped to QPS for bioanalysis (the method and details will be included in the final report) as shown below:Frontage Laboratories Attn: Sample Management 700 Pennsylvania DriveExton, PA 1943Email: Sample_Management@frontagelab.com Phone: (610) 232-0100Attn: Sample Coordinator/Lan Li QPS, LLC3 Innovation WayNewark, DE 19711Tel: (302) 369-5120Fax: (302) 369-5602Email: sample@qps.com"
    },
    "headers": {
        "TAK": "TAK-188",
        "TKD": "TKD-BCS-01991"
    }
}

###

###
POST http://localhost:7071/api/startOrchestrator
content-type: application/json

{
    "content": {
        "Document Title: Examination of the Stability of TAK-188 in Mouse, Monkey, and Human Plasma": "Document Version: 1.0Effective Date: 14 Apr 2023 14:22:20 (GMT-04:00)Signed By : Guo, Yukuang (mne9509) Decision : ApprovedDecision Date : 14 Apr 2023 13:52:28 (GMT-04:00)Role : Approver Purpose : ApprovalMeaning Of Signature : I approve this documentSigned By : Zhu, Xiaochun Sean (UBN7028) Decision : ApprovedDecision Date : 14 Apr 2023 14:22:06 (GMT-04:00)Role : Approver Purpose : ApprovalMeaning Of Signature : I approve this documentSignature Manifestation Page 1 of 1NONCLINICAL STUDY PROTOCOLMetabolism Identification Title:Examination of the Stability of TAK-188 in Mouse, Monkey, and Human Plasma Protocol:TKD-BCS-01991Testing Facility:Takeda Development Center Americas, Inc.35 Landsdowne StreetCambridge, MA 02139 USAStudy Director:Yukuang Guo Ph (312) 722-0479Proposed Study Dates:Experimental Start: 01 April 2023Experimental End: 01 July 2023",
        "INTRODUCTION": "CCR8 expression is upregulated on a highly immunosuppressive subset of regulatory T cells (Tregs) in multiple cancer types. TAK-188 is an Antibody Drug Conjugate (ADC) targeting CCR8. TAK-188 is designed specifically for depleting Tregs and boosting the immune system to produce an antitumoral effect.",
        "STUDY OBJECTIVE": "The objective of this study is to examine the plasma stability of TAK-188 in vitro in fresh mouse, monkey, and human plasma.",
        "REGULATORY GUIDELINES": "",
        "Good Laboratory Practice Compliance": "This study will not be conducted in accordance with the Code of Federal Regulations, Title 21, Part 58: Good Laboratory Practice for Nonclinical Laboratory Studies, issued by the United States Food and Drug Administration. However, this study will be conducted according to standard departmental practices.",
        "Amendments To, and Deviations From, the Protocol": "Any changes to the protocol will be described in a written protocol amendment approved by the Study Director specified in this protocol and recorded in the raw data at Takeda Development Center Americas, Inc. (TDCA) (Cambridge, MA, USA). Any deviations from the protocol will be documented appropriately and listed in the final report.",
        "TESTING FACILITY": "All aspects of this study will be conducted by personnel of TDCA (Cambridge, MA, USA).",
        "STUDY PERSONNEL": "Table 1 lists personnel involved in this study.",
        "PROPOSED STUDY SCHEDULE": "Table 2 provides the proposed study schedule.",
        "Table 2Proposed Study Schedule": "91440052510Study ComponentProposed DateExperimental start date:01 April 2023Experimental end date:01 July 202390525641553",
        "MATERIALS": "Unless otherwise stated, all analytical reagents will be at least of high-performance liquid chromatography (HPLC) reagent grade. Unless otherwise noted, all chemicals, with the exception of the test article (TAK-188) will be purchased from Sigma-Aldrich Corp (St. Louis, MO, USA) or supplied by personnel of TDCA’s Lab Operations group. All reagents, with the exception of the test article, will be less than 5 years old or formulated by personnel of TDCA’s Lab Operations group.",
        "Test Article": "TAK-188 will be supplied by personnel of TDCA’s Sample Bank and stored at approximately −20°C.The test article is early, research-grade material, which has not been completely characterized for identity, purity, and stability, and which does not have a Certificate of Analysis. The identity, storage temperature, lot (batch) numbers, and formulation requirements will be documented in the study file.",
        "Test System": "Fresh mouse, monkey, and human plasma will be purchased from external vendor (information will be provided in the final report).",
        "Reagents and Instruments": "The reagents and instruments used in this study will be specified in the raw data and final report.",
        "ASSAY METHODOLOGY": "",
        "Plasma incubation": "The experimental procedure and final conditions will be specified in the final report. The incubation will be run in triplicates. The incubation conditions are shown in Table 3.",
        "Table 3Incubation Conditions": "91440052480Matrix:Fresh plasmaSpecies:Mouse, monkey, humanTime (hours):0, 4, and 24Concentration (µg/mL):100Incubator Conditions:5% CO2, ~93% humidity, 37°CShaking Rate (rpm):7591440041438rpm: revolutions per minute.",
        "BIOANALYSIS": "The monkey and human samples will be shipped to Frontage Laboratories and mouse samples will be shipped to QPS for bioanalysis (the method and details will be included in the final report) as shown below:Frontage Laboratories Attn: Sample Management 700 Pennsylvania DriveExton, PA 1943Email: Sample_Management@frontagelab.com Phone: (610) 232-0100Attn: Sample Coordinator/Lan Li QPS, LLC3 Innovation WayNewark, DE 19711Tel: (302) 369-5120Fax: (302) 369-5602Email: sample@qps.com",
        "DATA INTERPRETATION AND REPORTING": "The Study Director, with participation by other contributing scientists, as appropriate, will prepare a report describing, but not necessarily be limited to, the following: a summary of the study, study objectives, materials and methods, and results and interpretation, including any appropriate tables, figures, and/or appendices.",
        "REMEASUREMENT AND ADOPTION OF THE DATA": "If the Study Director believes that a certain event (eg, technical error, instrumentation problem, or scientifically unexpected phenomena) may have affected the reliability of the present study, the Study Director may deem it necessary to repeat the experiment(s) in the study. The reasons for repeating any steps of an experiment, and for adoption or exclusion of the results, will be noted in the raw data and the final report.",
        "ARCHIVING": "All study data, including the protocol (with any amendments and deviations), final report, study file, laboratory study notebooks, instrument printouts, and other raw data or materials from the study will be maintained at TDCA according to standard departmental procedures.Title:    Examination of the Stability of TAK-188 in Mouse, Monkey, and Human Plasma",
        "PROTOCOL APPROVAL": "(see electronic signature page)91440042931Yukuang Guo Study Director Scientist IDrug Metabolism and Pharmacokinetics(see electronic signature page)91440041471Xiaochun Sean Zhu Scientific DirectorDrug Metabolism and Pharmacokinetics"
    },
    "headers": {
        "TAK": "TAK-188",
        "TKD": "TKD-BCS-01991"
    }
}
